// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *Homepage → Main News*
 */
export interface HomepageDocumentDataMainNewsItem {
  /**
   * title field in *Homepage → Main News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_news[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Homepage → Main News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_news[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * isButton field in *Homepage → Main News*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.main_news[].isbutton
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isbutton: prismic.BooleanField;

  /**
   * Button Title field in *Homepage → Main News*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_news[].button_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_title: prismic.RichTextField;

  /**
   * Image field in *Homepage → Main News*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_news[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * isFirstNews field in *Homepage → Main News*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: homepage.main_news[].isfirstnews
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isfirstnews: prismic.BooleanField;
}

/**
 * Item in *Homepage → Header Left NavBar*
 */
export interface HomepageDocumentDataHeaderLeftNavbarItem {
  /**
   * title field in *Homepage → Header Left NavBar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.header_left_navbar[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Item in *Homepage → Header Right NavBar*
 */
export interface HomepageDocumentDataHeaderRightNavbarItem {
  /**
   * title field in *Homepage → Header Right NavBar*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.header_right_navbar[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

type HomepageDocumentDataSlices3Slice = ScheduleSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Main News field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_news[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main_news: prismic.GroupField<Simplify<HomepageDocumentDataMainNewsItem>> /**
   * title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  title: prismic.RichTextField;

  /**
   * description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * favicon field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.favicon
   * - **Tab**: MetaData
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  favicon: prismic.ImageField<never> /**
   * Header Left NavBar field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.header_left_navbar[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  header_left_navbar: prismic.GroupField<
    Simplify<HomepageDocumentDataHeaderLeftNavbarItem>
  >;

  /**
   * Header Logo field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.header_logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * Header Right NavBar field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.header_right_navbar[]
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  header_right_navbar: prismic.GroupField<
    Simplify<HomepageDocumentDataHeaderRightNavbarItem>
  > /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices3[]
   * - **Tab**: Schedule
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices3: prismic.SliceZone<HomepageDocumentDataSlices3Slice> /**
   * Next Match Title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.next_match_title
   * - **Tab**: Next Match
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */;
  next_match_title: prismic.RichTextField;

  /**
   * Next Match Date field in *Homepage*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.next_match_date
   * - **Tab**: Next Match
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  next_match_date: prismic.DateField;

  /**
   * Next Match Location field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.next_match_location
   * - **Tab**: Next Match
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  next_match_location: prismic.RichTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Schedule → Primary*
 */
export interface ScheduleSliceDefaultPrimary {
  /**
   * Day field in *Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.primary.day
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  day: prismic.RichTextField;

  /**
   * Category field in *Schedule → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.primary.category
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  category: prismic.RichTextField;

  /**
   * Date field in *Schedule → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Training Slots field in *Schedule → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule.primary.training_slots[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  training_slots: prismic.GroupField<
    Simplify<ScheduleDocumentDataTrainingSlotsItem>
  >;
}

/**
 * Default variation for Schedule Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Schedule*
 */
type ScheduleSliceVariation = ScheduleSliceDefault;

/**
 * Schedule Shared Slice
 *
 * - **API ID**: `schedule`
 * - **Description**: Schedule
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleSlice = prismic.SharedSlice<
  "schedule",
  ScheduleSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataMainNewsItem,
      HomepageDocumentDataHeaderLeftNavbarItem,
      HomepageDocumentDataHeaderRightNavbarItem,
      HomepageDocumentDataSlices3Slice,
      AllDocumentTypes,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      ScheduleSlice,
      ScheduleDocumentDataTrainingSlotsItem,
      ScheduleSliceDefaultPrimary,
      ScheduleSliceVariation,
      ScheduleSliceDefault,
    };
  }
}
